In [44]:
import pandas as pd

In [59]:
df = pd.read_csv(r"C:\Users\harip\Downloads\retail_sales_dataset.csv")

In [60]:
df[df.isnull().all(axis=1)]

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4063,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df['order_id'].isnull().sum()

30

In [62]:
df = df[~df.isnull().all(axis=1)]

In [63]:
df.isnull().sum()

order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                      130
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                 110
unit_price                 0
discount_pct             137
sales_amount               0
profit                     0
shipping_cost              0
payment_method             0
customer_satisfaction    348
return_flag                0
order_status               0
days_to_ship             100
dtype: int64

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4310 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4280 non-null   object
 1   order_date             4280 non-null   object
 2   customer_id            4280 non-null   object
 3   customer_name          4280 non-null   object
 4   age                    4150 non-null   float64
 5   gender                 4280 non-null   object
 6   region                 4280 non-null   object
 7   city                   4280 non-null   object
 8   product_category       4280 non-null   object
 9   product_name           4280 non-null   object
 10  quantity               4170 non-null   float64
 11  unit_price             4280 non-null   float64
 12  discount_pct           4143 non-null   float64
 13  sales_amount           4280 non-null   float64
 14  profit                 4280 non-null   float64
 15  shipping_cost          4280 non-null   float64
 16  payment_method         4280 non-null   object
 17  customer_satisfaction  3932 non-null   float64
 18  return_flag            4280 non-null   object
 19  order_status           4280 non-null   object
 20  days_to_ship           4180 non-null   float64
dtypes: float64(9), object(12)
memory usage: 707.2+ KB

In [64]:
print(df.shape)
df = df[~df.isnull().all(axis=1)]
print(df.shape)

(4280, 21)
(4280, 21)

In [65]:
df.isnull().sum()

order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                      130
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                 110
unit_price                 0
discount_pct             137
sales_amount               0
profit                     0
shipping_cost              0
payment_method             0
customer_satisfaction    348
return_flag                0
order_status               0
days_to_ship             100
dtype: int64

In [67]:
df[df['quantity'].isnull()][['order_id','unit_price','discount_pct','sales_amount','profit']].head(10)

      order_id  unit_price  discount_pct  sales_amount   profit
23   ORD-02986      478.05          0.02        621.35   290.90
37   ORD-02031     1431.29          0.04       1929.40   819.70
61   ORD-01273     1490.57          0.13       1761.29   922.64
71   ORD-02850     5493.74          0.20       6967.21  1809.32
76   ORD-01278     3288.50          0.01       4673.02  1513.25
141  ORD-00540     1644.33          0.31       1186.66   470.96
162  ORD-03777     1486.09          0.11       1967.10   719.18
193  ORD-03310    11000.34          0.04       9272.71  1339.40
289  ORD-00322    59036.18          0.38      48186.78  5073.50
302  ORD-03014     8903.55          0.12      11991.16  1852.66

In [68]:
sample = df[df['quantity'].notnull()].head(10)
sample['calculated_qty'] = sample['sales_amount'] / (sample['unit_price'] * (1 - sample['discount_pct']))
sample[['quantity', 'calculated_qty', 'unit_price', 'discount_pct', 'sales_amount']]

   quantity  calculated_qty  unit_price  discount_pct  sales_amount
0       8.0             NaN      346.32           NaN       4043.14
1       8.0       11.579354      858.66          0.08       9147.31
2       4.0        4.937663    25941.32          0.14     110156.97
3       9.0       14.305158    22071.92          0.17     262066.11
4       1.0        1.466890      320.06          0.31        323.95
5       2.0        2.973670      949.50          0.22       2202.33
6       3.0        3.085352      329.03          0.02        994.87
7       1.0        1.593712     1356.60          0.01       2140.41
8       8.0        9.057003      495.77          0.37       2828.82
9       9.0        7.603848     2128.77          0.10      14568.16

In [69]:
df['quantity'].describe()

count    4170.000000
mean        7.379856
std        43.578352
min        -1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max       999.000000
Name: quantity, dtype: float64

In [70]:
df.groupby('product_category')['quantity'].median()

product_category
Beauty         5.0
Books          5.0
Clothing       5.0
Electronics    5.5
Furniture      6.0
Groceries      6.0
Sports         5.0
Name: quantity, dtype: float64

In [71]:
df[df['quantity'] < 0]

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
112,ORD-03804,2024-07-12,CUST42902,Rahul Kumar,50.0,Other,South,Hyderabad,Groceries,Sugar,...,84.21,0.13,125.78,8.90,47.91,Cash on Delivery,4.0,False,Delivered,2.0
1129,ORD-03770,2024-06-28,CUST96876,Nikhil Sharma,35.0,Other,South,Bangalore,Electronics,Smartwatch,...,21887.79,0.34,27456.59,3466.29,71.52,Debit Card,5.0,False,Delivered,9.0
1472,ORD-03766,2024-06-27,CUST36068,Aarav Singh,30.0,Other,East,Bhubaneswar,Clothing,Jeans,...,3154.09,0.01,4594.66,1520.00,69.59,UPI,3.0,False,Delivered,9.0
1527,ORD-00533,2020-08-23,CUST56679,Shreya Sharma,33.0,Other,North,Ludhiana,Clothing,Saree,...,774.58,0.31,670.73,287.27,49.67,UPI,3.0,False,Delivered,6.0
2112,ORD-04108,2024-11-18,CUST02996,Sunita Mehta,42.0,Male,South,Chennai,Clothing,Jacket,...,3079.53,0.11,2711.38,987.61,68.17,Credit Card,5.0,False,Cancelled,1.0
2670,ORD-02090,2022-07-09,CUST03478,Sunita Mishra,33.0,Female,Central,Nagpur,Books,Comic Book,...,1491.38,0.11,2043.42,838.22,72.14,UPI,5.0,False,Delivered,3.0

In [72]:
df[df['quantity'] > 50].sort_values('quantity', ascending=False).head(10)

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
242,ORD-00751,2020-12-07,CUST41385,Rohan Patel,32.0,M,North,Amritsar,Books,Cook Book,...,403.63,0.15,203951.50,80603.27,48.70,EMI,5.0,False,Delivered,1.0
1012,ORD-01242,2021-07-14,CUST50699,Rohan Chatterjee,16.0,Female,East,Patna,Books,Self-Help Book,...,545.25,0.02,729651.06,258878.20,54.26,Debit Card,4.0,False,Delivered,2.0
1112,ORD-00539,2020-08-25,CUST19345,Ananya Pillai,53.0,Other,Central,Indore,Clothing,Jacket,...,2567.40,0.31,2281458.22,899209.60,74.46,EMI,3.0,False,Delivered,5.0
1138,ORD-01025,2021-04-09,CUST16923,Nisha Bhat,36.0,M,North,Amritsar,Sports,Tennis Racket,...,9380.72,0.29,7936261.20,1739854.00,72.62,Net Banking,4.0,False,Delivered,4.0
1700,ORD-00689,2020-11-08,CUST06352,Sunita Singh,43.0,Other,North,Delhi,Groceries,Rice (5kg),...,195.29,0.10,140042.31,9617.93,60.48,Credit Card,NaN,False,Delivered,7.0
2178,ORD-01732,2022-02-08,CUST51801,Shreya Gupta,18.0,MALE,South,Bangalore,Books,Fiction Novel,...,709.64,0.16,533420.31,141347.64,82.77,Debit Card,2.0,True,Returned,2.0
2582,ORD-00809,2021-01-05,CUST99388,Ritu Kapoor,33.0,Male,South,Chennai,Clothing,Jeans,...,3280.13,0.03,2586345.13,921794.60,83.69,EMI,1.0,True,Returned,7.0
3865,ORD-02560,2023-01-14,CUST90788,Kavya Kapoor,999.0,Female,South,Kochi,Electronics,Tablet,...,18619.45,0.00,17360314.17,2445648.43,82.19,EMI,1.0,False,Delivered,5.0

In [73]:
df[df['quantity'] < 0][['order_id','quantity','product_category','sales_amount']]

       order_id  quantity product_category  sales_amount
112   ORD-03804      -1.0        Groceries        125.78
1129  ORD-03770      -1.0      Electronics      27456.59
1472  ORD-03766      -1.0         Clothing       4594.66
1527  ORD-00533      -1.0         Clothing        670.73
2112  ORD-04108      -1.0         Clothing       2711.38
2670  ORD-02090      -1.0            Books       2043.42

In [74]:
df[df['quantity'] > 50][['order_id','quantity','product_category','sales_amount']].sort_values('quantity', ascending=False)

       order_id  quantity product_category  sales_amount
242   ORD-00751     999.0            Books     203951.50
1012  ORD-01242     999.0            Books     729651.06
1112  ORD-00539     999.0         Clothing    2281458.22
1138  ORD-01025     999.0           Sports    7936261.20
1700  ORD-00689     999.0        Groceries     140042.31
2178  ORD-01732     999.0            Books     533420.31
2582  ORD-00809     999.0         Clothing    2586345.13
3865  ORD-02560     999.0      Electronics   17360314.17

In [75]:
import numpy as np
df['quantity'] = df['quantity'].replace([-1, 999], np.nan)

In [76]:
df['quantity'].isnull().sum()

124

In [77]:
df['quantity_imputed'] = df['quantity'].isnull()
median_qty = df['quantity'].median()
df['quantity'] = df['quantity'].fillna(median_qty)

In [78]:
df['quantity'].isnull().sum()

0

In [79]:
df['quantity_imputed'].sum()

124

In [80]:
df['discount_pct'].describe()

count    4143.000000
mean        0.202085
std         0.118095
min         0.000000
25%         0.100000
50%         0.210000
75%         0.310000
max         0.400000
Name: discount_pct, dtype: float64

In [81]:
df['discount_pct'].value_counts().sort_index().tail(10)

discount_pct
0.31     89
0.32     95
0.33    130
0.34    102
0.35     99
0.36    129
0.37    129
0.38    101
0.39    116
0.40     54
Name: count, dtype: int64

In [82]:
df['discount_pct'].value_counts().sort_index().head(10)

discount_pct
0.00     45
0.01    115
0.02    107
0.03    113
0.04    122
0.05    108
0.06    112
0.07    105
0.08     83
0.09    106
Name: count, dtype: int64

In [83]:
df['discount_pct_imputed'] = df['discount_pct'].isnull()
median_discount = df['discount_pct'].median()
df['discount_pct'] = df['discount_pct'].fillna(median_discount)

In [84]:
df['discount_pct'].isnull().sum()

0

In [85]:
df['discount_pct_imputed'].sum()

137

In [86]:
df['age'].describe()

count    4150.000000
mean       35.335181
std        35.709382
min        -7.000000
25%        26.000000
50%        34.000000
75%        42.000000
max       999.000000
Name: age, dtype: float64

In [87]:
df[df['age'] < 0][['order_id','age']]

       order_id  age
42    ORD-00415 -6.0
199   ORD-03298 -5.0
424   ORD-00270 -5.0
534   ORD-02511 -5.0
1143  ORD-03701 -1.0
1291  ORD-03830 -2.0
1798  ORD-03015 -4.0
3142  ORD-03218 -5.0
3481  ORD-03619 -7.0
3717  ORD-02976 -2.0
3719  ORD-03952 -7.0
4070  ORD-00990 -4.0
4134  ORD-03701 -1.0

In [88]:
df[df['age'] > 100][['order_id','age']]

       order_id    age
44    ORD-00757  999.0
148   ORD-00073  999.0
466   ORD-04036  999.0
1010  ORD-04145  999.0
1411  ORD-02359  150.0
2265  ORD-04007  150.0
3865  ORD-02560  999.0
4168  ORD-01529  150.0

In [89]:
df.loc[(df['age'] < 0) | (df['age'] > 100), 'age'] = np.nan

In [90]:
df['age'].isnull().sum()

151

In [91]:
df['age_imputed'] = df['age'].isnull()
median_age = df['age'].median()
df['age'] = df['age'].fillna(median_age)

In [92]:
df['age'].isnull().sum()

0

In [93]:
df['age_imputed'].sum()

151

In [94]:
df['customer_satisfaction'].describe()

count    3932.000000
mean        3.016531
std         1.413127
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: customer_satisfaction, dtype: float64

In [95]:
df['customer_satisfaction'].value_counts().sort_index()

customer_satisfaction
1.0    776
2.0    779
3.0    767
4.0    824
5.0    786
Name: count, dtype: int64

In [96]:
df['feedback_given'] = df['customer_satisfaction'].notnull()

In [97]:
df['feedback_given'].value_counts()

feedback_given
True     3932
False     348
Name: count, dtype: int64

In [98]:
df['order_status'].value_counts()

order_status
Delivered    2666
Returned      623
Cancelled     339
Shipped       318
Pending       178
delivered     121
shipped        16
cancelled      13
pending         6
Name: count, dtype: int64

In [99]:
df[df['days_to_ship'].isnull()]['order_status'].value_counts()

order_status
Delivered    61
Returned     14
Shipped      13
Pending       6
Cancelled     4
delivered     2
Name: count, dtype: int64

In [100]:
df['order_status'] = df['order_status'].str.strip().str.capitalize()

In [101]:
df['order_status'].value_counts()

order_status
Delivered    2787
Returned      623
Cancelled     352
Shipped       334
Pending       184
Name: count, dtype: int64

In [102]:
should_have_shipped = df['order_status'].isin(['Delivered', 'Shipped', 'Returned'])
df['days_to_ship_imputed'] = df['days_to_ship'].isnull() & should_have_shipped

median_days = df['days_to_ship'].median()
df.loc[df['days_to_ship_imputed'], 'days_to_ship'] = median_days

In [103]:
df['days_to_ship'].isnull().sum()

10

In [104]:
df['days_to_ship_imputed'].sum()

90

In [105]:
df.isnull().sum()

order_id                   0
order_date                 0
customer_id                0
customer_name              0
age                        0
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                   0
unit_price                 0
discount_pct               0
sales_amount               0
profit                     0
shipping_cost              0
payment_method             0
customer_satisfaction    348
return_flag                0
order_status               0
days_to_ship              10
quantity_imputed           0
discount_pct_imputed       0
age_imputed                0
feedback_given             0
days_to_ship_imputed       0
dtype: int64

In [106]:
df['order_id'].duplicated().sum()

80

In [107]:
dup_ids = df[df['order_id'].duplicated(keep=False)]['order_id'].unique()
df[df['order_id'].isin(dup_ids)].sort_values('order_id').head(20)

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship,quantity_imputed,discount_pct_imputed,age_imputed,feedback_given,days_to_ship_imputed
590,ORD-00051,2020-01-20,CUST27973,Shreya Pillai,13.0,Male,South,Hyderabad,Beauty,Perfume,...,Credit Card,1.0,False,Shipped,8.0,False,False,False,True,False
3899,ORD-00051,2020-01-20,CUST27973,Shreya Pillai,13.0,Male,South,Hyderabad,Beauty,Perfume,...,Credit Card,1.0,False,Shipped,8.0,False,False,False,True,False
1654,ORD-00084,2020-02-03,CUST43984,Meera Kumar,58.0,Male,North,Ludhiana,Clothing,Kurta,...,UPI,5.0,False,Delivered,5.0,False,False,False,True,False
1111,ORD-00084,2020-02-03,CUST43984,Meera Kumar,58.0,Male,North,Ludhiana,Clothing,Kurta,...,UPI,5.0,False,Delivered,5.0,False,False,False,True,False
738,ORD-00144,2020-02-27,CUST57714,Shreya Kumar,37.0,Female,South,Chennai,Furniture,Chair,...,Cash on Delivery,5.0,False,Delivered,6.0,False,True,False,True,False
1957,ORD-00144,2020-02-27,CUST57714,Shreya Kumar,37.0,Female,South,Chennai,Furniture,Chair,...,Cash on Delivery,5.0,False,Delivered,6.0,False,True,False,True,False
128,ORD-00268,2020-04-27,CUST64785,Sunita Reddy,32.0,Female,West,Mumbai,Books,Cook Book,...,Credit Card,1.0,False,Cancelled,5.0,False,False,False,True,False
774,ORD-00268,2020-04-27,CUST64785,Sunita Reddy,32.0,Female,West,Mumbai,Books,Cook Book,...,Credit Card,1.0,False,Cancelled,5.0,False,False,False,True,False
941,ORD-00305,2020-05-12,CUST10300,Vikram Joshi,35.0,Other,East,Bhubaneswar,Sports,Yoga Mat,...,EMI,5.0,False,Delivered,10.0,False,False,False,True,False
715,ORD-00305,2020-05-12,CUST10300,Vikram Joshi,35.0,Other,East,Bhubaneswar,Sports,Yoga Mat,...,EMI,5.0,False,Delivered,10.0,False,False,False,True,False
2187,ORD-00324,2020-05-22,CUST46595,Amit Bhat,12.0,Male,North,Amritsar,Clothing,T-Shirt,...,Net Banking,1.0,False,Delivered,4.0,False,False,False,True,False
1624,ORD-00324,2020-05-22,CUST46595,Amit Bhat,12.0,Male,North,Amritsar,Clothing,T-Shirt,...,Net Banking,1.0,False,Delivered,4.0,False,False,False,True,False
4089,ORD-00344,2020-05-28,CUST09269,Shreya Kumar,40.0,f,West,Pune,Groceries,Sugar,...,Cash on Delivery,1.0,False,Cancelled,10.0,False,False,False,True,False
3230,ORD-00344,2020-05-28,CUST09269,Shreya Kumar,40.0,f,West,Pune,Groceries,Sugar,...,Cash on Delivery,1.0,False,Cancelled,10.0,False,False,False,True,False
806,ORD-00384,2020-06-12,CUST60562,Kavya Rao,25.0,Male,North,Ludhiana,Clothing,Dress,...,Cash on Delivery,1.0,False,Delivered,7.0,False,False,False,True,False
414,ORD-00384,2020-06-12,CUST60562,Kavya Rao,25.0,Male,North,Ludhiana,Clothing,Dress,...,Cash on Delivery,1.0,False,Delivered,7.0,False,False,False,True,False
923,ORD-00402,2020-06-21,CUST55018,Vikram Nair,37.0,Other,South,Chennai,Electronics,Headphones,...,Debit Card,5.0,False,Delivered,6.0,False,False,False,True,False
85,ORD-00402,2020-06-21,CUST55018,Vikram Nair,37.0,Other,South,Chennai,Electronics,Headphones,...,Debit Card,5.0,False,Delivered,6.0,False,False,False,True,False
169,ORD-00490,2020-08-04,CUST00642,Kavya Das,40.0,m,South,Chennai,Furniture,Wardrobe,...,EMI,3.0,False,Delivered,6.0,False,False,False,True,False
1713,ORD-00490,2020-08-04,CUST00642,Kavya Das,40.0,m,South,Chennai,Furniture,Wardrobe,...,EMI,3.0,False,Delivered,6.0,False,False,False,True,False

In [108]:
df = df.drop_duplicates(subset='order_id', keep='first')

In [109]:
df['order_id'].duplicated().sum()

0

In [110]:
df.shape

(4200, 26)

In [111]:
df['gender'].value_counts()

gender
Other     1419
Male      1178
Female    1172
male        67
MALE        61
f           55
F           53
m           53
M           49
FEMALE      48
female      45
Name: count, dtype: int64

In [112]:
def standardize_gender(g):
    g = str(g).strip().upper()
    if g in ['M', 'MALE']:
        return 'Male'
    elif g in ['F', 'FEMALE']:
        return 'Female'
    elif g == 'OTHER':
        return 'Other'
    else:
        return g

df['gender'] = df['gender'].apply(standardize_gender)

In [113]:
df['gender'].value_counts()

gender
Other     1419
Male      1408
Female    1373
Name: count, dtype: int64

In [114]:
for col in ['region', 'city', 'product_category', 'payment_method', 'return_flag']:
    print(col, '->', df[col].unique())
    print()

region -> ['Central' 'West' 'North' 'East' 'South']

city -> ['Raipur' 'Mumbai' 'Surat' 'Ahmedabad' 'Nagpur' 'Bhopal' 'Amritsar'
 'Patna' 'Ludhiana' 'Pune' 'Kochi' 'Bangalore' 'Guwahati' 'Delhi'
 'Chennai' 'Indore' 'Chandigarh' 'Bhubaneswar' 'Kolkata' 'Hyderabad']

product_category -> ['Groceries' 'Beauty' 'Furniture' 'Books' 'Clothing' 'Electronics'
 'Sports']

payment_method -> ['Debit Card' 'EMI' 'Net Banking' 'Cash on Delivery' 'Credit Card' 'UPI']

return_flag -> [True False]

In [115]:
df[['unit_price', 'sales_amount', 'profit', 'shipping_cost']].describe()

         unit_price  sales_amount        profit  shipping_cost
count   4200.000000  4.200000e+03  4.200000e+03    4200.000000
mean   10702.729695  6.292138e+04  1.179028e+04      63.378790
std    17408.776463  3.195126e+05  5.335219e+04      18.317527
min       50.260000  3.945000e+01  1.560000e+00      -4.290000
25%      680.817500  2.472295e+03  7.120700e+02      50.827500
50%     2246.005000  9.647895e+03  3.169875e+03      63.460000
75%    12828.977500  5.052485e+04  1.051096e+04      75.655000
max    79957.920000  1.736031e+07  2.445648e+06     133.350000

In [116]:
df[df['sales_amount'] > 1000000][['order_id', 'quantity', 'quantity_imputed', 'unit_price', 'sales_amount', 'profit']]

,order_id,quantity,quantity_imputed,unit_price,sales_amount,profit
1112,ORD-00539,5.0,True,2567.40,2281458.22,899209.60
1138,ORD-01025,5.0,True,9380.72,7936261.20,1739854.00
2379,ORD-03003,10.0,False,76450.07,1182709.24,198109.98
2582,ORD-00809,5.0,True,3280.13,2586345.13,921794.60
2891,ORD-02969,10.0,False,75218.46,1071676.26,126516.22
3667,ORD-03792,10.0,False,63505.68,1033433.55,141319.32
3865,ORD-02560,5.0,True,18619.45,17360314.17,2445648.43

In [117]:
df[df['shipping_cost'] < 0]

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship,quantity_imputed,discount_pct_imputed,age_imputed,feedback_given,days_to_ship_imputed
1878,ORD-03203,2023-10-17,CUST79007,Rahul Chatterjee,47.0,Other,North,Amritsar,Furniture,Bookshelf,...,Credit Card,3.0,False,Delivered,2.0,False,False,False,True,False
2012,ORD-00576,2020-09-15,CUST60901,Amit Mishra,38.0,Male,North,Delhi,Furniture,Bookshelf,...,Credit Card,3.0,False,Delivered,9.0,False,False,False,True,False

In [118]:
df[df['shipping_cost'] < 0][['order_id', 'shipping_cost', 'region', 'product_category']]

       order_id  shipping_cost region product_category
1878  ORD-03203          -3.11  North        Furniture
2012  ORD-00576          -4.29  North        Furniture

In [119]:
df.loc[df['shipping_cost'] < 0, 'shipping_cost'] = np.nan
df['shipping_cost_imputed'] = df['shipping_cost'].isnull()
median_shipping = df['shipping_cost'].median()
df['shipping_cost'] = df['shipping_cost'].fillna(median_shipping)

In [120]:
df['shipping_cost'].isnull().sum()

0

In [121]:
df['shipping_cost_imputed'].sum()

2

In [122]:
trustworthy = df[~df['order_id'].isin(['ORD-00539','ORD-01025','ORD-00809','ORD-02560'])]
median_margin = (trustworthy['profit'] / trustworthy['sales_amount']).median()
print(median_margin)

0.2679187118332973

In [123]:
corrupted_ids = ['ORD-00539', 'ORD-01025', 'ORD-00809', 'ORD-02560']
mask = df['order_id'].isin(corrupted_ids)

df['sales_amount_recalculated'] = mask

df.loc[mask, 'sales_amount'] = df.loc[mask, 'quantity'] * df.loc[mask, 'unit_price'] * (1 - df.loc[mask, 'discount_pct'])
df.loc[mask, 'profit'] = df.loc[mask, 'sales_amount'] * median_margin

In [124]:
df[mask][['order_id', 'quantity', 'unit_price', 'discount_pct', 'sales_amount', 'profit']]

,order_id,quantity,unit_price,discount_pct,sales_amount,profit
1112,ORD-00539,5.0,2567.40,0.31,8857.5300,2373.098028
1138,ORD-01025,5.0,9380.72,0.29,33301.5560,8922.109986
2582,ORD-00809,5.0,3280.13,0.03,15908.6305,4262.219791
3865,ORD-02560,5.0,18619.45,0.00,93097.2500,24942.495295

In [125]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True)
df['order_date'].min()

Timestamp('2020-01-01 00:00:00')

In [126]:
df['order_date'].max()

Timestamp('2024-12-30 00:00:00')

In [127]:
df['Month'] = df['order_date'].dt.month
df['Year'] = df['order_date'].dt.year

bins = [0, 17, 25, 35, 45, 55, 100]
labels = ['Under 18', '18-25', '26-35', '36-45', '46-55', '55+']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [128]:
df['return_flag'].dtype

dtype('O')

In [129]:
df['age_group'].value_counts()

age_group
26-35       1436
36-45       1100
18-25        614
46-55        579
Under 18     312
55+          154
Name: count, dtype: int64

In [130]:
df['return_flag'].unique()

array([True, False], dtype=object)

In [131]:
df['returned'] = df['return_flag'].astype(int)

In [132]:
df['returned'].value_counts()

returned
0    3588
1     612
Name: count, dtype: int64

In [133]:
df.to_csv('clean_sales.csv', index=False)

In [134]:
df.shape

(4200, 32)

In [135]:
df.columns.tolist()

['order_id',
 'order_date',
 'customer_id',
 'customer_name',
 'age',
 'gender',
 'region',
 'city',
 'product_category',
 'product_name',
 'quantity',
 'unit_price',
 'discount_pct',
 'sales_amount',
 'profit',
 'shipping_cost',
 'payment_method',
 'customer_satisfaction',
 'return_flag',
 'order_status',
 'days_to_ship',
 'quantity_imputed',
 'discount_pct_imputed',
 'age_imputed',
 'feedback_given',
 'days_to_ship_imputed',
 'shipping_cost_imputed',
 'sales_amount_recalculated',
 'Month',
 'Year',
 'age_group',
 'returned']

In [136]:
import os
os.path.abspath("clean_sales.csv")

'C:\\Users\\harip\\python\\clean_sales.csv'

In [137]:
!pip install sqlalchemy pymysql --quiet

In [139]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Hari1503@127.0.0.1:3308/sales_db")

df.to_sql('sales', con=engine, if_exists='append', index=False)

4200

In [140]:
SELECT order_id, order_date, age, quantity, customer_satisfaction, days_to_ship, feedback_given, sales_amount_recalculated FROM sales LIMIT 5;

SyntaxError: invalid syntax (2041915267.py, line 1)